// src/App.svelte
<!--
  App — root component. Wires up SPEC §5 interaction contract.
-->
<script>
  import DappledLight from './lib/components/DappledLight.svelte';
  import Article from './lib/components/Article.svelte';
  import { useSunToggle } from './lib/useSunToggle.js';

  const { toggle, attach } = useSunToggle();

  // $effect.pre runs synchronously BEFORE paint on mount — matches
  // React useLayoutEffect. Guarantees keydown listener is attached by
  // the time Playwright's page.goto() returns.
  $effect.pre(() => {
    const cleanup = attach();
    return cleanup;
  });
</script>

<div class="app-root" onclick={toggle} style="min-height: 100vh;" role="presentation">
  <DappledLight />
  <Article />
</div>

// src/App.jsx
import { onMount, onCleanup } from 'solid-js';
import DappledLight from './components/DappledLight.jsx';
import Article from './components/Article.jsx';
import { useSunToggle } from './hooks/useSunToggle.js';

export default function App() {
  const { toggle, attach } = useSunToggle();

  // Solid's onMount runs after DOM but is scheduled synchronously —
  // for Playwright test stability, this attaches before goto returns.
  onMount(() => {
    const cleanup = attach();
    onCleanup(cleanup);
  });

  return (
    <div class="app-root" onClick={toggle} style={{ 'min-height': '100vh' }}>
      <DappledLight />
      <Article />
    </div>
  );
}
