// app/app.vue
<script setup>
/**
 * App root — Nuxt 4 auto-imports composables/components.
 *
 * SPEC §11 cross-framework pitfall discipline:
 *   - useSunToggle owns state + toggle logic (no DOM listener)
 *   - keydown listener attached in this file's client-side eager block
 *     BEFORE hydration completes so Playwright's keyboard.press('Space')
 *     is caught even when fired immediately after page.goto()
 *   - Root <div @click> handles bubbled clicks (no document listener)
 *   - window.__sunlitReady flag lets Playwright waitForFunction sync
 */
const { toggle } = useSunToggle();

// Eager client attach — fires before onMounted, before hydration finishes.
// Nuxt equivalent of React's useLayoutEffect trick from SPEC §11.
if (import.meta.client) {
  const onKeydown = (event) => {
    if (event.code === 'Space') {
      event.preventDefault();
      toggle();
    }
  };
  window.addEventListener('keydown', onKeydown);
  window.__sunlitReady = true;

  onBeforeUnmount(() => {
    window.removeEventListener('keydown', onKeydown);
    delete window.__sunlitReady;
  });
}
</script>

<template>
  <div class="app-root" @click="toggle" :style="{ minHeight: '100vh' }">
    <DappledLight />
    <Article />
  </div>
</template>

// src/App.jsx
/**
 * App — root component.
 * Preact 10 uses React-compatible hooks via preact/compat.
 * Cross-framework pitfall discipline (SPEC §11):
 *   - useLayoutEffect for keydown listener → attached before Playwright's page.goto returns
 *   - DOM (body.classList) as single source of truth
 *   - Root <div onClick> handles bubbled clicks (no document-level listener)
 */
import DappledLight from './components/DappledLight.jsx';
import Article from './components/Article.jsx';
import { useSunToggle } from './hooks/useSunToggle.js';

export default function App() {
  const { toggle } = useSunToggle();
  return (
    <div className="app-root" onClick={toggle} style={{ minHeight: '100vh' }}>
      <DappledLight />
      <Article />
    </div>
  );
}
